name: Build + Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:10.0
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install jq
        run: |
          apt-get update
          apt-get install jq -y

      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: NuGet
          path: .artifacts

      - name: Release - GitHub
        run: ./build/release-github.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} .artifacts

      - name: NuGet.org login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Release - NuGet.org
        run: ./build/release-nuget.sh ${{steps.login.outputs.NUGET_API_KEY}}
